+ module 2
js-tasks-ru/jsbasic-20201022_79217466052 pull request #3
Opened 2020-11-02 12:24 UTC by lisiza

2020-11-02 12:48 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-11-02 13:34 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Определите, пуст ли объект
+ объект с удалённым свойством - пустой
+ если у объекта есть хоть одно свойство, то он не пустой
+ {} должен вернуть true
+ объект со свойством undefined должен считаться не пустым
```
```diff
Создайте калькулятор
+ должно складывать числа
+ должно умножать числа
```
```diff
Функция sumSalary(salaries)
+ должна складывать все зарплаты
+ должна возвращать 0 если нет свойств с зарплатами
+ должна игнорировать свойства других типов
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2020-11-03 12:46 UTC, koalex requested changes
Исправь замечания и добавь меня заново в ревью

2020-11-03 12:46 UTC, koalex commented on 0-module/1-task/index.js
> +  return +m + +n;
+ - лишнее

2020-11-03 12:46 UTC, koalex commented on 2-module/3-task/index.js
> +    return(this.a + this.b);
скобки не обязатаельно

2020-11-03 12:46 UTC, koalex commented on 3-module/5-task/index.js
> +  console.log(result);
удали строку 21 `console.log(result);`

2020-11-03 12:56 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-11-03 13:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-11-03 14:42 UTC, koalex approved these changes

2020-11-03 14:43 UTC, merged